name: Release build

on:
  push

  # release:
  #   types: [published]

jobs:
  # apple_m1:
  #   name: Apple ARM
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: aarch64-apple-darwin
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         use-cross: true
  #         command: build
  #         args: --release --target aarch64-apple-darwin

  # apple_x86_x64:
  #   name: Apple Intel
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-apple-darwin
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         use-cross: true
  #         command: build
  #         args: --release --target x86_64-apple-darwin

  linux_x86_x64:
    name: Linux x86_x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Move artifact to zip
        run: zip fxa-x86_64-unknown-linux-gnu.zip target/release/fxa
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: fxa-x86_64-unknown-linux-gnu.zip

  # windows_x86_x64:
  #   name: Windows x86_x64
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-pc-windows-msvc
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         use-cross: true
  #         command: build
  #         args: --release --target x86_64-pc-windows-msvc
